<a href="https://colab.research.google.com/github/Nikita018/Notes/blob/master/Notebooks/Covariance_Matrix_concepts.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [39]:
'''
Clarifying the concept of covariance - covariance shows how 2 variables vary together. In a covariance matrix, the diagonal values are variance and the other values are covariance. 
Cov Matrix is a square symmetric matrix.Range of cov : -infinity to infinity.
If we apply mean centering and make it a unit vector, the value is called correlation value. Range of cor : -1 to +1. Corr value of 0 means that the vectors are orthogonal to each other i.e. independent of each other
'''


array([[1, 3],
       [3, 1],
       [2, 2],
       [4, 4],
       [6, 6],
       [7, 3],
       [2, 2]])

In [75]:
import numpy as np
x0 = [1,3,2,4,6,7,2]
x1 = [3,1,2,4,6,3,2]
# X = np.vstack((x1, x2)).T
X = np.array([x0,x1]).T
X

array([[1, 3],
       [3, 1],
       [2, 2],
       [4, 4],
       [6, 6],
       [7, 3],
       [2, 2]])

In [24]:
X.shape

(7, 2)

In [25]:
X[:,1]

array([3, 1, 2, 4, 6, 3, 2])

In [12]:
X[:,0]

array([1, 3, 2, 4, 6, 7, 2])

In [54]:
# 1. Direct Covariance Matrix
CM = np.matmul(X.T,X)
print("Cov Matrix", CM)


Cov Matrix [[119  87]
 [ 87  79]]


In [66]:
# 2.Normalized Cov Matrix
from numpy import linalg as LA
x0 = [1.0,3.0,2.0,4.0,6.0,7.0,2.0]
x1 = [3.0,1.0,2.0,4.0,6.0,3.0,2.0]
# X = np.vstack((x1, x2)).T
X = np.array([x0,x1]).T
x0_norm = LA.norm(X[:,0],2)
x1_norm = LA.norm(X[:,1],2)
X[:,0] = X[:,0]/x0_norm
X[:,1] = X[:,1]/x1_norm
print("x0_norm : ",x0_norm)
print("x1_norm : ",x1_norm)
CM_2norm = np.matmul(X.T,X)
print("cov matrix of normalized matrix",CM_2norm)

x0_norm :  10.908712114635714
x1_norm :  8.888194417315589
cov matrix of normalized matrix [[1.         0.89728876]
 [0.89728876 1.        ]]


In [65]:
X

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

In [64]:
X[:,0]

array([0, 0, 0, 0, 0, 0, 0])

In [68]:
#mean-center cov matrix
x0 = [1.0,3.0,2.0,4.0,6.0,7.0,2.0]
x1 = [3.0,1.0,2.0,4.0,6.0,3.0,2.0]
X = np.array([x0,x1]).T
X

array([[1., 3.],
       [3., 1.],
       [2., 2.],
       [4., 4.],
       [6., 6.],
       [7., 3.],
       [2., 2.]])

In [70]:
mean_x0 = np.mean(X[:,0])
mean_x1 = np.mean(X[:,1])
mean_cen_x0 = X[:,0] - mean_x0
mean_cen_x1 = X[:,1] - mean_x1
X_mean_cen= np.array([mean_cen_x0,mean_cen_x1]).T
x0_norm = LA.norm(X_mean_cen[:,0],2)
x1_norm = LA.norm(X_mean_cen[:,1],2)
X_mean_cen[:,0] = X_mean_cen[:,0]/x0_norm
X_mean_cen[:,1] = X_mean_cen[:,1]/x1_norm
# Find cov
CM_2norm = np.matmul(X_mean_cen.T,X_mean_cen)
CM_2norm

array([[1.        , 0.55034954],
       [0.55034954, 1.        ]])

In [74]:
x0 = [1.0,3.0,2.0,4.0,6.0,7.0,2.0]
x1 = [3.0,1.0,2.0,4.0,6.0,3.0,2.0]
np.corrcoef(x0,x1)
# df = as.DataFrame([x0,x1])
# df.head()
# np.corr(x0,x1)

array([[1.        , 0.55034954],
       [0.55034954, 1.        ]])